language: node_js
node_js:
  - "8"
install:
  - cd ..
  - git init
  - git remote add origin https://github.com/eigenmethod/mam.git
  - git pull origin master
  - npm install
script:
  - npm start conduit
  - rm conduit/.gitignore
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: .
  on:
    branch: master
notifications:
  slack: mam-mol:Z7vokFhXaSrMlPXzq6L93bUj
